version: "3.9"
services:
  ui:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PROJECT_DIR: "${PROJECT_DIR}"
    container_name: ui_matt
    environment:
      NODE_ENV: "production"
      PROJECT_DIR: "${PROJECT_DIR}"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PORT: "${UI_PORT}"
      LETSENCRYPT_HOST: "${VIRTUAL_HOST}"
      LETSENCRYPT_EMAIL: "${LETSENCRYPT_EMAIL}"
    ports:
      - "${UI_PORT}:${UI_PORT}"
    networks:
      - proxy
      - app
    volumes:
      - .:${PROJECT_DIR}:z
    command: /bin/sh -c "chmod +x ./start.sh && ./start.sh"
networks:
  proxy:
    name: nginx-proxy
    external: true
  app:
