FROM node:16-alpine

# Set working directory
ARG PROJECT_DIR
ARG VIRTUAL_PORT
WORKDIR ${PROJECT_DIR}

# Install global packages
RUN yarn global add serve

# Copy required files
COPY --chown=node:node package.json yarn.lock dist serve.json  ./

# Set port
EXPOSE ${VIRTUAL_PORT}
